auto: true

#markdown: rdiscount
highlighter: 'rouge'
#paginate: 8
permalink: /:title

title: Le Fabuleux Destin d'Yange
url: http://camscofie.github.io
feed: /atom.xml
author_info: <a href="http://camscofie.github.io/">Yange</a>
